# Generated by Django 2.2.2 on 2019-06-23 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='copies',
            new_name='available_copies',
        ),
        migrations.AddField(
            model_name='books',
            name='users_lended',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
