# Generated by Django 2.2.2 on 2019-06-23 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0002_auto_20190623_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='users_lended',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
