# Generated by Django 2.2.2 on 2019-06-23 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0003_auto_20190623_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='users_lended',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
